"""Python type-stubs for the `Unsendable` pyclass."""

class Unsendable:
    other: Unsendable
    def __new__(cls) -> Unsendable: ...
    def __traverse__(self, visit) -> None: ...
    def __clear__(self) -> None: ...
