[package]
name = "unsendable_gc"
version = "0.0.1"
edition = "2021"

[lib]
name = "unsendable_gc"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "^0.19.0", features = ["extension-module"] }
